from django.urls import path

from . import guardian_views, university_views, views

app_name = "accounts"

urlpatterns = [
    # pages
    path("login/", views.login_page, name="login"),
    # guardians: a phone number and a WhatsApp code, no password
    path("guardian/", guardian_views.guardian_login_page, name="guardian_login"),
    path("guardian/logout/", guardian_views.guardian_logout, name="guardian_logout"),
    path("api/guardian/start/", guardian_views.api_guardian_start,
         name="api_guardian_start"),
    path("api/guardian/resend/", guardian_views.api_guardian_resend,
         name="api_guardian_resend"),
    path("api/guardian/verify/", guardian_views.api_guardian_verify,
         name="api_guardian_verify"),
    path("api/guardian/child/", guardian_views.api_guardian_switch_child,
         name="api_guardian_switch_child"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup_page, name="signup"),
    path("signup/university/", views.university_signup_page,
         name="university_signup"),
    path("forgot/", views.forgot_password_page, name="forgot"),
    path("invite/<str:token>/", views.invite_page, name="invite"),
    path("complete/", views.complete_profile, name="complete_profile"),
    path("face/", views.face_capture_page, name="face_capture"),
    path("profile/", views.profile_page, name="profile"),
    # university
    path("institutes/", university_views.institutes_page, name="institutes"),
    path("api/institutes/", university_views.api_institutes, name="api_institutes"),
    path("api/institutes/invite/", university_views.api_institute_invite,
         name="api_institute_invite"),
    path("api/institutes/<oid:pk>/approve/", university_views.api_institute_approve,
         name="api_institute_approve"),
    path("api/institutes/<oid:pk>/reject/", university_views.api_institute_reject,
         name="api_institute_reject"),
    path("api/institutes/<oid:pk>/update/", university_views.api_institute_update,
         name="api_institute_update"),
    path("api/institutes/<oid:pk>/disciplines/",
         university_views.api_institute_disciplines,
         name="api_institute_disciplines"),
    path("api/institutes/focus/", university_views.api_switch_institute,
         name="api_switch_institute"),
    # ajax
    path("api/login/", views.api_login, name="api_login"),
    path("api/signup/start/", views.api_signup_start, name="api_signup_start"),
    path("api/signup/university/start/", views.api_university_signup_start,
         name="api_university_signup_start"),
    path("api/signup/university/verify/", views.api_university_signup_verify,
         name="api_university_signup_verify"),
    path("api/affiliating-bodies/", views.api_affiliating_bodies,
         name="api_affiliating_bodies"),
    path("api/seeded-universities/", views.api_seeded_universities,
         name="api_seeded_universities"),
    path("api/signup/verify/", views.api_signup_verify, name="api_signup_verify"),
    path("api/signup/resend/", views.api_signup_resend, name="api_signup_resend"),
    path("api/invite/<str:token>/accept/", views.api_invite_accept, name="api_invite_accept"),
    path("api/forgot/start/", views.api_forgot_start, name="api_forgot_start"),
    path("api/forgot/confirm/", views.api_forgot_confirm, name="api_forgot_confirm"),
    path("api/profile/update/", views.api_profile_update, name="api_profile_update"),
    path("api/profile/organisation/", views.api_organisation_update,
         name="api_organisation_update"),
    path("api/profile/login-email/", views.api_login_email_update,
         name="api_login_email_update"),
    path("api/profile/disciplines/", views.api_add_disciplines,
         name="api_add_disciplines"),
    path("api/profile/disciplines/<str:code>/contents/",
         views.api_discipline_contents, name="api_discipline_contents"),
    path("api/profile/disciplines/remove/", views.api_remove_discipline,
         name="api_remove_discipline"),
    # The university's own coverage. Parallel paths to the three above, under
    # a different noun so neither reads as the other.
    path("api/profile/coverage/", views.api_add_coverage,
         name="api_add_coverage"),
    path("api/profile/coverage/<str:code>/contents/",
         views.api_coverage_contents, name="api_coverage_contents"),
    path("api/profile/coverage/remove/", views.api_remove_coverage,
         name="api_remove_coverage"),
    path("api/profile/password/", views.api_change_password, name="api_change_password"),
    path("api/profile/reset-device/", views.api_reset_device, name="api_reset_device"),
    path("api/face/enrol/", views.api_face_enrol, name="api_face_enrol"),
    path("api/check-email/", views.api_check_email, name="api_check_email"),
]
