import datetime as dt
import uuid
from pathlib import Path

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

from academics.models import Batch, StudentProfile, Subject


def new_token():
    return uuid.uuid4().hex


class AttendanceSession(models.Model):
    """
    One 'attendance request' generated by a teacher when they walk into a class.
    The teacher's GPS fix is captured here and becomes the centre of the geo-fence.
    """

    class Status(models.TextChoices):
        OPEN = "OPEN", "Open"
        CLOSED = "CLOSED", "Closed"
        CANCELLED = "CANCELLED", "Cancelled"

    token = models.CharField(max_length=32, unique=True, default=new_token, db_index=True)
    teacher = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="sessions_created"
    )
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name="sessions")
    batch = models.ForeignKey(Batch, on_delete=models.CASCADE, related_name="sessions")

    # geo-fence centre (teacher's position at generation time)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    accuracy_m = models.FloatField(default=0)
    radius_m = models.PositiveIntegerField(default=50)

    note = models.CharField(max_length=140, blank=True, help_text="Room / topic")
    session_date = models.DateField(default=timezone.localdate, db_index=True)
    expected_count = models.PositiveIntegerField(default=0)

    status = models.CharField(max_length=10, choices=Status.choices, default=Status.OPEN)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    expires_at = models.DateTimeField(db_index=True)
    closed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["subject", "batch", "session_date"]),
            models.Index(fields=["teacher", "-created_at"]),
        ]

    def __str__(self):
        return f"{self.subject.code} · {self.batch.label} · {self.created_at:%d %b %H:%M}"

    # ---- state ------------------------------------------------------------ #
    @property
    def is_expired(self):
        return timezone.now() >= self.expires_at

    @property
    def is_open(self):
        return self.status == self.Status.OPEN and not self.is_expired

    @property
    def seconds_left(self):
        return max(int((self.expires_at - timezone.now()).total_seconds()), 0)

    @property
    def effective_status(self):
        if self.status == self.Status.CANCELLED:
            return "CANCELLED"
        if self.status == self.Status.CLOSED or self.is_expired:
            return "CLOSED"
        return "OPEN"

    @property
    def mark_url(self):
        return f"{settings.SITE_URL}/attendance/mark/{self.token}/"

    @property
    def present_count(self):
        return self.records.filter(status__in=["PRESENT", "MANUAL"]).count()

    @property
    def manual_count(self):
        """
        Of those present, how many a teacher entered by hand.

        A subset of `present_count`, never a third bucket — MANUAL is one of
        the two statuses that count as present.
        """
        return self.records.filter(status="MANUAL").count()

    @property
    def percentage(self):
        if not self.expected_count:
            return 0.0
        return round(self.present_count * 100.0 / self.expected_count, 2)

    def close(self, when=None):
        if self.status == self.Status.OPEN:
            self.status = self.Status.CLOSED
            self.closed_at = when or timezone.now()
            if self.expires_at > timezone.now():
                self.expires_at = self.closed_at
            self.save(update_fields=["status", "closed_at", "expires_at"])
        return self

    @property
    def validity_minutes(self):
        """How long this link was set to live, from creation to expiry."""
        return max(0, round((self.expires_at - self.created_at).total_seconds() / 60))

    @property
    def latest_allowed_expiry(self):
        """
        The furthest `expires_at` may ever be pushed, counted from creation.

        The cap is on the *total* window, not on one extension. Capping each
        extension instead would let a teacher click "+5 minutes" six times and
        keep a link alive all afternoon — which is the thing the ceiling exists
        to prevent.
        """
        from django.conf import settings

        cap = int(settings.ATTENDANCE.get("MAX_EXPIRY_MIN", 30))
        return self.created_at + dt.timedelta(minutes=cap)

    def extend(self, minutes):
        """
        Push the expiry out, never past the total-validity ceiling.

        Returns the session. Callers that need to tell the teacher they hit the
        ceiling should compare `expires_at` before and after, or check
        `latest_allowed_expiry` first.
        """
        base = max(self.expires_at, timezone.now())
        self.expires_at = min(base + dt.timedelta(minutes=minutes),
                              self.latest_allowed_expiry)
        if self.status == self.Status.CLOSED:
            self.status = self.Status.OPEN
            self.closed_at = None
        self.save(update_fields=["expires_at", "status", "closed_at"])
        return self


class AttendanceRecord(models.Model):
    class Status(models.TextChoices):
        PRESENT = "PRESENT", "Present"
        MANUAL = "MANUAL", "Marked by teacher"
        ABSENT = "ABSENT", "Absent"

    session = models.ForeignKey(AttendanceSession, on_delete=models.CASCADE, related_name="records")
    student = models.ForeignKey(
        StudentProfile, on_delete=models.CASCADE, related_name="attendance_records"
    )
    status = models.CharField(max_length=10, choices=Status.choices, default=Status.PRESENT)
    marked_at = models.DateTimeField(default=timezone.now, db_index=True)

    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    accuracy_m = models.FloatField(null=True, blank=True)
    distance_m = models.FloatField(null=True, blank=True)

    ip = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.CharField(max_length=400, blank=True)
    device_fingerprint = models.CharField(max_length=64, blank=True, db_index=True)

    marked_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,
        related_name="records_marked", help_text="Set when a teacher overrides.",
    )
    remark = models.CharField(max_length=200, blank=True)

    class Meta:
        ordering = ["-marked_at"]
        constraints = [
            models.UniqueConstraint(fields=["session", "student"], name="uniq_record_per_session"),
        ]
        indexes = [
            models.Index(fields=["student", "-marked_at"]),
            models.Index(fields=["session", "status"]),
        ]

    def __str__(self):
        return f"{self.student} · {self.session.subject.code} · {self.status}"

    @property
    def is_present(self):
        return self.status in (self.Status.PRESENT, self.Status.MANUAL)


class MarkAttempt(models.Model):
    """Every rejected attempt is stored — invaluable for spotting proxy attendance."""

    class Reason(models.TextChoices):
        OUT_OF_RANGE = "RANGE", "Outside geo-fence"
        EXPIRED = "EXPIRED", "Link expired"
        NOT_ENROLLED = "ENROL", "Not enrolled"
        WRONG_BATCH = "BATCH", "Wrong batch"
        DUPLICATE = "DUP", "Already marked"
        NO_LOCATION = "NOLOC", "Location unavailable"
        LOW_ACCURACY = "ACC", "GPS accuracy too poor"
        DEVICE_MISMATCH = "DEVICE", "Different device"
        SHARED_DEVICE = "SHARED", "Device already used by another student"
        NOT_STUDENT = "ROLE", "Not a student account"
        CANCELLED = "CANCELLED", "Session cancelled"
        BATCH_ARCHIVED = "ARCHIVED", "Batch archived"
        OK = "OK", "Accepted"

    session = models.ForeignKey(
        AttendanceSession, on_delete=models.CASCADE, related_name="attempts", null=True, blank=True
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,
        related_name="mark_attempts",
    )
    reason = models.CharField(max_length=12, choices=Reason.choices)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    accuracy_m = models.FloatField(null=True, blank=True)
    distance_m = models.FloatField(null=True, blank=True)
    ip = models.GenericIPAddressField(null=True, blank=True)
    device_fingerprint = models.CharField(max_length=64, blank=True)
    detail = models.CharField(max_length=250, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.user} · {self.reason}"


class AbsenceReason(models.Model):
    """
    A student's explanation for missing one class, and its review.

    Deliberately does **not** change attendance. An approved reason is context
    for staff, not a correction to the record: percentages, exports, dashboards
    and the low-attendance alerts all continue to count the class as missed.
    Keeping it inert means the number still answers "was this student in the
    room", and an effect can be layered on later without rewriting history.
    """

    class Status(models.TextChoices):
        PENDING = "PENDING", "Awaiting review"
        APPROVED = "APPROVED", "Approved"
        REJECTED = "REJECTED", "Rejected"

    session = models.ForeignKey(
        AttendanceSession, on_delete=models.CASCADE, related_name="absence_reasons"
    )
    student = models.ForeignKey(
        StudentProfile, on_delete=models.CASCADE, related_name="absence_reasons"
    )
    reason = models.TextField(max_length=1000)
    status = models.CharField(max_length=10, choices=Status.choices, default=Status.PENDING)
    submitted_at = models.DateTimeField(default=timezone.now, db_index=True)

    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,
        related_name="absence_reviews",
    )
    reviewed_at = models.DateTimeField(null=True, blank=True)
    review_remark = models.CharField(max_length=300, blank=True)

    class Meta:
        ordering = ["-submitted_at"]
        constraints = [
            # One explanation per class. A rejected reason is final, so this
            # also enforces "no resubmission" at the database level rather than
            # relying on the view to remember.
            models.UniqueConstraint(
                fields=["session", "student"], name="uniq_absence_reason_per_session"
            ),
        ]
        indexes = [
            models.Index(fields=["status", "-submitted_at"]),
            models.Index(fields=["student", "-submitted_at"]),
        ]

    def __str__(self):
        return f"{self.student} · {self.session.subject.code} · {self.status}"

    @property
    def is_pending(self):
        return self.status == self.Status.PENDING


class PlannedAbsence(models.Model):
    """
    An absence a student knows about in advance — illness, travel, a wedding.

    Filed before the classes exist, so it cannot hang off an AttendanceSession
    the way AbsenceReason does. It covers a date range and, by default, every
    subject the student takes; they may narrow it to specific subjects.

    Like AbsenceReason it is a record, not a correction: attendance figures are
    untouched whatever the outcome.
    """

    student = models.ForeignKey(
        StudentProfile, on_delete=models.CASCADE, related_name="planned_absences"
    )
    from_date = models.DateField(db_index=True)
    to_date = models.DateField(db_index=True)
    reason = models.TextField(max_length=1000)
    # Empty means "every subject the student takes"; the decision rows below
    # record what that resolved to when it was filed, so later enrolment
    # changes cannot silently widen or narrow an approved absence.
    all_subjects = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=timezone.now, db_index=True)
    cancelled_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-from_date", "-created_at"]
        indexes = [
            models.Index(fields=["student", "-from_date"]),
            models.Index(fields=["from_date", "to_date"]),
        ]

    def __str__(self):
        return f"{self.student} · {self.from_date}–{self.to_date}"

    @property
    def is_cancelled(self):
        return self.cancelled_at is not None

    @property
    def days(self):
        return (self.to_date - self.from_date).days + 1

    def covers(self, session_date, subject_id):
        """Does this absence excuse a class of `subject_id` on `session_date`?"""
        if self.is_cancelled:
            return False
        if not (self.from_date <= session_date <= self.to_date):
            return False
        return self.decisions.filter(subject_id=subject_id).exists()

    @property
    def overall_status(self):
        """
        One word for a request that is decided per subject.

        Deliberately pessimistic: anything still pending reads as pending, and
        a single rejection is worth surfacing rather than hiding behind a
        majority of approvals.
        """
        statuses = {d.status for d in self.decisions.all()}
        if not statuses:
            return AbsenceReason.Status.PENDING
        if AbsenceReason.Status.PENDING in statuses:
            return AbsenceReason.Status.PENDING
        if AbsenceReason.Status.REJECTED in statuses:
            return AbsenceReason.Status.REJECTED
        return AbsenceReason.Status.APPROVED


class PlannedAbsenceDecision(models.Model):
    """
    One subject's verdict on a planned absence.

    A request spanning four subjects is four decisions, each made by a teacher
    allocated to that subject for the student's batch (or by the HoD or head).
    Splitting it this way keeps "the teacher decides about their own class"
    true even when the request covers classes that do not exist yet.
    """

    planned = models.ForeignKey(
        PlannedAbsence, on_delete=models.CASCADE, related_name="decisions"
    )
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE,
                                related_name="planned_absence_decisions")
    status = models.CharField(max_length=10, choices=AbsenceReason.Status.choices,
                              default=AbsenceReason.Status.PENDING)
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,
        related_name="planned_absence_reviews",
    )
    reviewed_at = models.DateTimeField(null=True, blank=True)
    review_remark = models.CharField(max_length=300, blank=True)

    class Meta:
        ordering = ["subject__code"]
        constraints = [
            models.UniqueConstraint(fields=["planned", "subject"],
                                    name="uniq_planned_decision_per_subject"),
        ]
        indexes = [models.Index(fields=["status"])]

    def __str__(self):
        return f"{self.planned} · {self.subject.code} · {self.status}"

    @property
    def is_pending(self):
        return self.status == AbsenceReason.Status.PENDING


def attachment_path(instance, filename):
    """
    Where one piece of evidence lives.

    Foldered by student and by which request it belongs to, so a human looking
    at the storage account can tell what they are looking at, and so deleting
    one request's evidence is a directory operation rather than a search. The
    stored name is a uuid: two students uploading "certificate.pdf" must not
    collide, and a filename a student chose is not something to put on a path.
    """
    owner = instance.reason_id or instance.planned_id or "orphan"
    kind = "reason" if instance.reason_id else "planned"
    suffix = Path(filename).suffix.lower()[:10]
    return f"absence/{kind}/{owner}/{uuid.uuid4().hex}{suffix}"


class AbsenceAttachment(models.Model):
    """
    Evidence a student attached to an absence request — a medical certificate,
    a travel ticket, a photograph of a letter.

    Hangs off *either* a per-class reason or a planned absence, never both and
    never neither. Two nullable foreign keys rather than a generic relation:
    contenttypes buys nothing here (there will never be a third kind of parent)
    and costs a join plus a table this database would rather not have.

    Like everything else in this feature it is inert — attaching a certificate
    does not move an attendance percentage.
    """

    reason = models.ForeignKey(
        AbsenceReason, on_delete=models.CASCADE, related_name="attachments",
        null=True, blank=True,
    )
    planned = models.ForeignKey(
        PlannedAbsence, on_delete=models.CASCADE, related_name="attachments",
        null=True, blank=True,
    )
    file = models.FileField(upload_to=attachment_path, max_length=300)
    # The name the student's own machine used. Kept separately because the
    # stored name is a uuid, and shown back to them so they can tell two
    # attachments apart.
    original_name = models.CharField(max_length=255)
    content_type = models.CharField(max_length=100, blank=True)
    size_bytes = models.PositiveIntegerField(default=0)
    uploaded_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["uploaded_at"]
        # No indexes declared here on purpose. A ForeignKey is indexed by
        # Django already, so `Index(fields=["reason"])` asks for a *second*
        # index on the same key under a different name — which MongoDB refuses
        # outright (IndexOptionsConflict), taking the whole migration with it.
        # Both lookups this model needs are covered by the FK indexes.

    def clean(self):
        # "Exactly one parent" would normally be a CheckConstraint, but this
        # database has no check constraints — Django would silently drop it and
        # leave a rule that reads as enforced and is not. Enforced here and in
        # save() instead, so it holds however the row is written.
        if bool(self.reason_id) == bool(self.planned_id):
            raise ValidationError(
                "An attachment belongs to exactly one absence request.")

    def save(self, *args, **kwargs):
        self.clean()
        return super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.original_name} ({self.size_bytes} bytes)"

    @property
    def is_image(self):
        return self.content_type.startswith("image/")

    @property
    def size_label(self):
        """A size a person can read, rather than a count of bytes."""
        kb = self.size_bytes / 1024
        return f"{kb:.0f} KB" if kb < 1024 else f"{kb / 1024:.1f} MB"


class FaceVerifyTicket(models.Model):
    """
    Permission to attempt face verification for one class, once.

    The geo-fence, the device lock, the enrolment and the window are all checked
    over HTTP before this exists. The socket then only has to ask "is this a
    valid, unspent ticket" — it never re-runs those rules, and more importantly
    a student cannot reach the matching socket without having passed them.

    The measured numbers are carried here rather than re-read from the browser
    later: a client that could restate its own distance after the check would
    make the geo-fence decorative.
    """

    session = models.ForeignKey(
        AttendanceSession, on_delete=models.CASCADE, related_name="face_tickets"
    )
    student = models.ForeignKey(
        StudentProfile, on_delete=models.CASCADE, related_name="face_tickets"
    )
    token = models.CharField(max_length=32, unique=True, default=new_token, db_index=True)

    # Exactly what check_mark_allowed measured, frozen at issue time.
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    accuracy_m = models.FloatField(null=True, blank=True)
    distance_m = models.FloatField(default=0)
    device_fingerprint = models.CharField(max_length=64, blank=True)
    ip = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.CharField(max_length=400, blank=True)

    attempts = models.PositiveIntegerField(default=0)
    used_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    expires_at = models.DateTimeField(db_index=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [models.Index(fields=["session", "student"])]

    def __str__(self):
        return f"{self.student} · {self.session.subject.code} · face ticket"

    @property
    def is_spent(self):
        return self.used_at is not None

    @property
    def is_expired(self):
        return timezone.now() >= self.expires_at

    @property
    def is_usable(self):
        return not self.is_spent and not self.is_expired


class ManualMarkRequest(models.Model):
    """
    A student the camera could not recognise, asking the teacher to look up.

    Only reachable once the geo-fence has passed, so the student is provably in
    the room — the question is identity, not presence, and the teacher standing
    in front of them is better placed to answer it than any model. The best
    frame is kept so the request is not just a name with no evidence.
    """

    class Status(models.TextChoices):
        PENDING = "PENDING", "Waiting for the teacher"
        APPROVED = "APPROVED", "Marked present"
        REJECTED = "REJECTED", "Refused"

    session = models.ForeignKey(
        AttendanceSession, on_delete=models.CASCADE, related_name="manual_requests"
    )
    student = models.ForeignKey(
        StudentProfile, on_delete=models.CASCADE, related_name="manual_mark_requests"
    )
    ticket = models.ForeignKey(
        FaceVerifyTicket, on_delete=models.SET_NULL, null=True, blank=True,
        related_name="manual_requests",
    )
    # Why the match never landed: no face, too dark, never close enough.
    reason = models.CharField(max_length=120, blank=True)
    best_score = models.FloatField(default=0)
    attempts = models.PositiveIntegerField(default=0)
    snapshot = models.ImageField(upload_to="manual_marks/", max_length=300,
                                 null=True, blank=True)

    status = models.CharField(max_length=10, choices=Status.choices,
                              default=Status.PENDING)
    decided_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,
        related_name="manual_marks_decided",
    )
    decided_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now, db_index=True)

    class Meta:
        ordering = ["-created_at"]
        constraints = [
            models.UniqueConstraint(fields=["session", "student"],
                                    name="uniq_manual_request_per_session"),
        ]
        indexes = [models.Index(fields=["session", "status"])]

    def __str__(self):
        return f"{self.student} · {self.session.subject.code} · {self.status}"
