# Generated by Django 5.2.16 on 2026-08-05 02:51

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('attendance', '0002_faceverifyticket_manualmarkrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_forms_sent', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_form', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRecipient',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='feedback.feedbackform')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to='academics.studentprofile')),
            ],
            options={
                'ordering': ['student__class_roll'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('rating', models.PositiveSmallIntegerField(default=0, help_text='1–5 stars')),
                ('remarks', models.TextField(blank=True, max_length=1000)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.feedbackform')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to='academics.studentprofile')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feedbackform',
            index=models.Index(fields=['-created_at'], name='feedback_fe_created_368b40_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackrecipient',
            index=models.Index(fields=['student', 'responded_at'], name='feedback_fe_student_1fa434_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedbackrecipient',
            constraint=models.UniqueConstraint(fields=('form', 'student'), name='uniq_feedback_recipient'),
        ),
        migrations.AddIndex(
            model_name='feedbackresponse',
            index=models.Index(fields=['form', 'submitted_at'], name='feedback_fe_form_id_b332c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedbackresponse',
            constraint=models.UniqueConstraint(fields=('form', 'student'), name='uniq_feedback_response_per_student'),
        ),
    ]
