# Generated by Django 5.1.15 on 2026-08-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='question_version',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
