# Generated by Django 5.2.16 on 2026-08-04 08:44

import accounts.models
import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_enrolled',
            field=models.BooleanField(default=False, help_text='Student has captured the three enrolment images.'),
        ),
        migrations.CreateModel(
            name='FaceEnrolment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_name', models.CharField(blank=True, max_length=40)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('reset_reason', models.CharField(blank=True, max_length=200)),
                ('reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_resets_performed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_enrolment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceSample',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose', models.CharField(choices=[('FRONT', 'Looking straight ahead'), ('LEFT', 'Turned slightly left'), ('RIGHT', 'Turned slightly right')], max_length=6)),
                ('image', models.ImageField(max_length=300, upload_to=accounts.models.face_image_path)),
                ('embedding', models.JSONField(default=list)),
                ('yaw', models.FloatField(default=0)),
                ('detect_score', models.FloatField(default=0)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='accounts.faceenrolment')),
            ],
            options={
                'ordering': ['pose'],
                'constraints': [models.UniqueConstraint(fields=('enrolment', 'pose'), name='uniq_face_sample_per_pose')],
            },
        ),
    ]
