# Generated by Django 5.1.15 on 2026-08-12 15:55

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitybatch',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='universitybatch',
            name='label',
            field=models.CharField(help_text='e.g. 2022-26', max_length=12),
        ),
        migrations.AlterField(
            model_name='universitydepartment',
            name='discipline',
            field=models.CharField(choices=[('AGRI', 'Agriculture, Veterinary & Allied Sciences'), ('DIPLOMA', 'Diploma (Polytechnic & ITI)'), ('ENGG', 'Engineering, Technology & Management'), ('GENERAL', 'General Courses (Arts, Science, Commerce)'), ('MEDICAL', 'Medical, Health Sciences, Ayush, Nursing & Paramedical'), ('PHARMACY', 'Pharmacy')], db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='universitydepartment',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='universitysubject',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
