# Generated by Django 5.1.15 on 2026-08-03 14:56

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('STUDENT', 'WhatsApp to student'), ('GUARDIAN', 'WhatsApp to guardian')], max_length=10)),
                ('name', models.CharField(help_text='Shown to staff when picking a template.', max_length=120)),
                ('twilio_name', models.SlugField(help_text='Lowercase letters, digits and underscores only.', max_length=120)),
                ('language', models.CharField(default='en', max_length=10)),
                ('category', models.CharField(default='UTILITY', max_length=20)),
                ('body', models.TextField(help_text='Uses {{placeholder}} names, not numbers.')),
                ('variable_order', models.JSONField(blank=True, default=list, help_text='Placeholder names in slot order: index 0 fills {{1}}.')),
                ('content_sid', models.CharField(blank=True, db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECEIVED', 'Received'), ('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled'), ('FAILED', 'Submission failed')], default='DRAFT', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, max_length=400)),
                ('last_error', models.CharField(blank=True, max_length=400)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_templates', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='accounts.institute')),
            ],
            options={
                'ordering': ['audience', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertCampaign',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('OVERALL', 'Overall attendance'), ('SUBJECT', 'Subject-specific')], default='OVERALL', max_length=10)),
                ('threshold', models.FloatField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('email_students', models.BooleanField(default=True)),
                ('whatsapp_students', models.BooleanField(default=False)),
                ('whatsapp_guardians', models.BooleanField(default=True)),
                ('email_subject', models.CharField(blank=True, max_length=250)),
                ('email_body', models.TextField(blank=True)),
                ('student_whatsapp_body', models.TextField(blank=True)),
                ('whatsapp_body', models.TextField(blank=True, help_text='Sent to the guardian.')),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('email_sent', models.PositiveIntegerField(default=0)),
                ('email_failed', models.PositiveIntegerField(default=0)),
                ('student_whatsapp_sent', models.PositiveIntegerField(default=0)),
                ('student_whatsapp_failed', models.PositiveIntegerField(default=0)),
                ('whatsapp_sent', models.PositiveIntegerField(default=0)),
                ('whatsapp_failed', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.institute')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='academics.subject')),
                ('guardian_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_campaigns', to='notifications.whatsapptemplate')),
                ('student_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_campaigns', to='notifications.whatsapptemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email to student'), ('WHATSAPP', 'WhatsApp to guardian'), ('WA_STUDENT', 'WhatsApp to student')], max_length=10)),
                ('target', models.CharField(help_text='Email address or phone number', max_length=150)),
                ('percentage', models.FloatField(default=0)),
                ('subject_line', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=10)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('provider_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.alertcampaign')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_deliveries', to='academics.studentprofile')),
            ],
            options={
                'ordering': ['student__class_roll', 'channel'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='notificatio_campaig_8f2d7c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='whatsapptemplate',
            constraint=models.UniqueConstraint(fields=('institute', 'twilio_name'), name='uniq_wa_template_name'),
        ),
    ]
