# Generated by Django 5.2.16 on 2026-08-04 15:56

import attendance.models
import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceVerifyTicket',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=attendance.models.new_token, max_length=32, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('distance_m', models.FloatField(default=0)),
                ('device_fingerprint', models.CharField(blank=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_tickets', to='attendance.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_tickets', to='academics.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualMarkRequest',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('best_score', models.FloatField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('snapshot', models.ImageField(blank=True, max_length=300, null=True, upload_to='manual_marks/')),
                ('status', models.CharField(choices=[('PENDING', 'Waiting for the teacher'), ('APPROVED', 'Marked present'), ('REJECTED', 'Refused')], default='PENDING', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_marks_decided', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_requests', to='attendance.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_mark_requests', to='academics.studentprofile')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_requests', to='attendance.faceverifyticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='faceverifyticket',
            index=models.Index(fields=['session', 'student'], name='attendance__session_180376_idx'),
        ),
        migrations.AddIndex(
            model_name='manualmarkrequest',
            index=models.Index(fields=['session', 'status'], name='attendance__session_cdce7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='manualmarkrequest',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='uniq_manual_request_per_session'),
        ),
    ]
